### ISSUE TITLE
Feature/플레이어 Input 구현

### ISSUE THREAD

**Issue by D0ryeon** [yarogono/DungeonEleven#34]
# 구현 상황
플레이어
- 스테이터스
- 이동 (방향키 <- , ->)
- 점프 (space)
- 피격 기능
애니메이션
- 이동(완료)
- 점프(구현했는데 작동 안함 수정해야됨)
- 떨어짐 모션(위와 동일)
 - 위 두개는 점프하면서 구현했습니다.
 - 이동시 애니메이션이 나오게 할 수 있는데 AnimationController를 사용하여 메소드를 작성하면 동작을 안합니다.
- 대쉬(애니메이션만 있음)
- 죽음(애니메이션만 있음) 오늘 구현 예정
- 피격(애니메이션만 있음) 오늘 구현 예정

# 남은 구현사항
피격 모션 설정
피격시 체력 감소 기능 구현
공격 기능 구현
공격모션 기능 구현

# 문제점
진행하면서 C#에 대한 이해도 자체가 부족함을 느꼈습니다.
스크립트 한장에 몰아서 public으로 필요한 Status를 인스펙터로 설정해주고 메소드와  애니메이션 조절하고 하는 건 할 수 있겠는데
이걸 강의처럼 스크립트를 잘게 나눠서 사용했을 때 스크립트를 어떻게 사용해야 되는가에 대한 이해도가 너무 부족했습니다.
그리고 event의 사용법 , status handler를 불러왔을 때 모든 값이 0으로 뜨는 문제 등 기초적인 이해도가 부족해서 생기는 문제가 많아서 구현에 어려움이 있었습니다. C# 공부를 더 해서 구현할 수 있도록 하겠습니다.

**Comment by yarogono** [comment]
공유 감사합니다!
